### ISSUE TITLE
Make sure tweet is acceptable length

### ISSUE THREAD

**Issue by pbgnz** [pbgnz/my-history-dosis#1]
Get this error when the tweet is longer than the limit:

```bash
Error at statuses/update Error: Tweet needs to be a bit shorter.
    at Object.exports.makeTwitError (C:\Users\pablo.gonzalez\Documents\cmder\my-history-dosis\node_modules\twit\lib\helpers.js:74:13)
    at onRequestComplete (C:\Users\pablo.gonzalez\Documents\cmder\my-history-dosis\node_modules\twit\lib\twitter.js:344:25)
    at Request.<anonymous> (C:\Users\pablo.gonzalez\Documents\cmder\my-history-dosis\node_modules\twit\lib\twitter.js:364:7)
    at Request.emit (events.js:215:7)
    at Gunzip.<anonymous> (C:\Users\pablo.gonzalez\Documents\cmder\my-history-dosis\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:299:28)
    at Gunzip.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  message: 'Tweet needs to be a bit shorter.',
  code: 186,
  allErrors: [ { code: 186, message: 'Tweet needs to be a bit shorter.' } ],
  twitterReply: { errors: [ [Object] ] },
  statusCode: 403
}
```

**Comment by pbgnz** [comment]
The maximum tweet length according to some google articles is 280 characters.
