### ISSUE TITLE
investigate bugs

### ISSUE THREAD

**Issue by pbgnz** [pbgnz/my-history-dosis#13]

**Comment by pbgnz** [comment]
```
internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ETIMEDOUT 151.101.137.140:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '151.101.137.140',
  port: 443
}
```

**Comment by pbgnz** [comment]
```
Error at downloading image: The Ryōunkaku in Tokyo, the tallest building in Japan from 1890 until the 1923 earthquake  TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:148:13)
    at Object.request (https.js:314:10)
    at Request.start (C:\Users\gonza\Documents\dev\my-history-dosis\node_modules\request\request.js:751:32)
    at Request.end (C:\Users\gonza\Documents\dev\my-history-dosis\node_modules\request\request.js:1505:10)
    at end (C:\Users\gonza\Documents\dev\my-history-dosis\node_modules\request\request.js:564:14)
    at Immediate._onImmediate (C:\Users\gonza\Documents\dev\my-history-dosis\node_modules\request\request.js:578:7)
    at processImmediate (internal/timers.js:456:21) {
  code: 'ERR_UNESCAPED_CHARACTERS'
}
Error at downloading image: maid at コンビニ  TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:148:13)
    at Object.request (https.js:314:10)
    at Request.start (C:\Users\gonza\Documents\dev\my-history-dosis\node_modules\request\request.js:751:32)
    at Request.end (C:\Users\gonza\Documents\dev\my-history-dosis\node_modules\request\request.js:1505:10)
    at end (C:\Users\gonza\Documents\dev\my-history-dosis\node_modules\request\request.js:564:14)
    at Immediate._onImmediate (C:\Users\gonza\Documents\dev\my-history-dosis\node_modules\request\request.js:578:7)
    at processImmediate (internal/timers.js:456:21) {
  code: 'ERR_UNESCAPED_CHARACTERS'
}
```

**Comment by pbgnz** [comment]
```sh
[Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: posts.hash
Emitted 'error' event on Statement instance at:
] {
  errno: 19,
  code: 'SQLITE_CONSTRAINT'
}
```
seems like the hash function is having collisions

**Comment by pbgnz** [comment]
```
internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

[Error: UNKNOWN: unknown error, write] {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'write'
}
```
